# Generated by Django 4.2.14 on 2024-07-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sell_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=55)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=55)),
                ('provider', models.CharField(max_length=50)),
                ('json_data', models.TextField()),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('-event_id',),
            },
        ),
    ]
